from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field
from app.schemas.schemas import TransactionStatus, TransactionType



class MpesaTransactionBase(BaseModel):
    merchant_request_id: str = Field(..., description="Safaricom MerchantRequestID")
    checkout_request_id: str = Field(..., description="Safaricom CheckoutRequestID")
    status: TransactionStatus
    offer_id: Optional[int] = None
    mpesa_receipt_number: Optional[str] = Field(None, description="Receipt number for successful txns")
    receiving_number: Optional[str]    = Field(None, description="MSISDN that received airtime/payment")
    paying_number: Optional[str]       = Field(None, description="MSISDN that funded the txn")
    amount: int                        = Field(..., gt=0, description="Transaction amount")
    transaction_date: datetime        = Field(..., description="Date/time of the M-Pesa transaction")
    result_code: int                  = Field(..., description="Daraja API result code")
    result_desc: str                  = Field(..., description="Daraja API result description")
    points_awarded: Optional[float] = None


class MpesaTransactionCreate(MpesaTransactionBase):
    """
    Schema for creating a new MpesaTransaction.
    Excludes autogenerated fields like id, created_at, updated_at.
    """
    pass


class MpesaTransactionRead(MpesaTransactionBase):
    """
    Schema for reading MpesaTransaction records.
    Includes all fields, and enables ORM parsing.
    """
    id: int                          = Field(..., description="Internal primary key")
    created_at: datetime            = Field(..., description="Record creation timestamp")
    updated_at: datetime            = Field(..., description="Record last-update timestamp")


class MpesaTransactionResponse(BaseModel):
    id: str
    mpesa_receipt_number: Optional[str]
    paying_number: Optional[str]
    receiving_number: Optional[str]
    amount: int
    status: TransactionStatus
    transaction_date: datetime