"""database init

Revision ID: 04607098664f
Revises: 
Create Date: 2025-09-01 22:44:22.140101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '04607098664f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bingwaoffer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('validity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('category', sa.Enum('data', 'sms', 'minutes', 'minutes_plus_data', 'combo', name='offercategory'), nullable=False),
    sa.Column('tag', sa.Enum('loyalty', 'popular', 'offer', name='bingwatags'), nullable=True),
    sa.Column('times_purchased', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bingwaoffer_active'), 'bingwaoffer', ['active'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_api_key'), 'clients', ['api_key'], unique=True)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=True)
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('opted_in', sa.Boolean(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_phone_number'), 'contact', ['phone_number'], unique=True)
    op.create_table('inspectionresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verdict', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('coverage_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('robots_txt_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('indexing_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_crawl_time', sa.DateTime(), nullable=False),
    sa.Column('page_fetch_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('indexing_result', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mobile_verdict', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rich_results_verdict', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspectionresult_page_url'), 'inspectionresult', ['page_url'], unique=False)
    op.create_table('intrusionlog',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('origin', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('referer', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('headers_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intrusionlog_id'), 'intrusionlog', ['id'], unique=False)
    op.create_index(op.f('ix_intrusionlog_ip'), 'intrusionlog', ['ip'], unique=False)
    op.create_index(op.f('ix_intrusionlog_method'), 'intrusionlog', ['method'], unique=False)
    op.create_index(op.f('ix_intrusionlog_origin'), 'intrusionlog', ['origin'], unique=False)
    op.create_index(op.f('ix_intrusionlog_path'), 'intrusionlog', ['path'], unique=False)
    op.create_table('loyaltyaccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_points', sa.Float(), nullable=False),
    sa.Column('points_earned', sa.Float(), nullable=False),
    sa.Column('total_amount_spent', sa.Float(), nullable=False),
    sa.Column('redeemed_points', sa.Float(), nullable=True),
    sa.Column('last_redeemed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loyaltyaccount_phone_number'), 'loyaltyaccount', ['phone_number'], unique=True)
    op.create_index(op.f('ix_loyaltyaccount_points_earned'), 'loyaltyaccount', ['points_earned'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mpesatransaction',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('merchant_request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checkout_request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='transactionstatus'), nullable=False),
    sa.Column('mpesa_receipt_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('receiving_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paying_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('points_awarded', sa.Float(), nullable=True),
    sa.Column('payment_reference_id', sa.Integer(), nullable=True),
    sa.Column('payment_type', sa.Enum('BINGWA_OFFER', 'AIRTIME', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('result_code', sa.Integer(), nullable=False),
    sa.Column('result_desc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mpesatransaction_checkout_request_id'), 'mpesatransaction', ['checkout_request_id'], unique=False)
    op.create_index(op.f('ix_mpesatransaction_id'), 'mpesatransaction', ['id'], unique=False)
    op.create_index(op.f('ix_mpesatransaction_merchant_request_id'), 'mpesatransaction', ['merchant_request_id'], unique=False)
    op.create_index(op.f('ix_mpesatransaction_mpesa_receipt_number'), 'mpesatransaction', ['mpesa_receipt_number'], unique=True)
    op.create_index(op.f('ix_mpesatransaction_paying_number'), 'mpesatransaction', ['paying_number'], unique=False)
    op.create_index(op.f('ix_mpesatransaction_payment_reference_id'), 'mpesatransaction', ['payment_reference_id'], unique=False)
    op.create_index(op.f('ix_mpesatransaction_points_awarded'), 'mpesatransaction', ['points_awarded'], unique=False)
    op.create_index(op.f('ix_mpesatransaction_receiving_number'), 'mpesatransaction', ['receiving_number'], unique=False)
    op.create_index(op.f('ix_mpesatransaction_result_code'), 'mpesatransaction', ['result_code'], unique=False)
    op.create_table('searchanalytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('page_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_searchanalytics_country'), 'searchanalytics', ['country'], unique=False)
    op.create_index(op.f('ix_searchanalytics_page_url'), 'searchanalytics', ['page_url'], unique=False)
    op.create_index(op.f('ix_searchanalytics_query'), 'searchanalytics', ['query'], unique=False)
    op.create_table('securitycode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sitemap',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_pending', sa.Boolean(), nullable=False),
    sa.Column('is_sitemaps_index', sa.Boolean(), nullable=False),
    sa.Column('last_submitted', sa.DateTime(), nullable=True),
    sa.Column('last_downloaded', sa.DateTime(), nullable=True),
    sa.Column('warnings', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_submitted', sa.Integer(), nullable=False),
    sa.Column('content_indexed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sitemap_id'), 'sitemap', ['id'], unique=False)
    op.create_index(op.f('ix_sitemap_path'), 'sitemap', ['path'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('super_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_index(op.f('ix_sitemap_path'), table_name='sitemap')
    op.drop_index(op.f('ix_sitemap_id'), table_name='sitemap')
    op.drop_table('sitemap')
    op.drop_table('securitycode')
    op.drop_index(op.f('ix_searchanalytics_query'), table_name='searchanalytics')
    op.drop_index(op.f('ix_searchanalytics_page_url'), table_name='searchanalytics')
    op.drop_index(op.f('ix_searchanalytics_country'), table_name='searchanalytics')
    op.drop_table('searchanalytics')
    op.drop_index(op.f('ix_mpesatransaction_result_code'), table_name='mpesatransaction')
    op.drop_index(op.f('ix_mpesatransaction_receiving_number'), table_name='mpesatransaction')
    op.drop_index(op.f('ix_mpesatransaction_points_awarded'), table_name='mpesatransaction')
    op.drop_index(op.f('ix_mpesatransaction_payment_reference_id'), table_name='mpesatransaction')
    op.drop_index(op.f('ix_mpesatransaction_paying_number'), table_name='mpesatransaction')
    op.drop_index(op.f('ix_mpesatransaction_mpesa_receipt_number'), table_name='mpesatransaction')
    op.drop_index(op.f('ix_mpesatransaction_merchant_request_id'), table_name='mpesatransaction')
    op.drop_index(op.f('ix_mpesatransaction_id'), table_name='mpesatransaction')
    op.drop_index(op.f('ix_mpesatransaction_checkout_request_id'), table_name='mpesatransaction')
    op.drop_table('mpesatransaction')
    op.drop_table('messages')
    op.drop_index(op.f('ix_loyaltyaccount_points_earned'), table_name='loyaltyaccount')
    op.drop_index(op.f('ix_loyaltyaccount_phone_number'), table_name='loyaltyaccount')
    op.drop_table('loyaltyaccount')
    op.drop_index(op.f('ix_intrusionlog_path'), table_name='intrusionlog')
    op.drop_index(op.f('ix_intrusionlog_origin'), table_name='intrusionlog')
    op.drop_index(op.f('ix_intrusionlog_method'), table_name='intrusionlog')
    op.drop_index(op.f('ix_intrusionlog_ip'), table_name='intrusionlog')
    op.drop_index(op.f('ix_intrusionlog_id'), table_name='intrusionlog')
    op.drop_table('intrusionlog')
    op.drop_index(op.f('ix_inspectionresult_page_url'), table_name='inspectionresult')
    op.drop_table('inspectionresult')
    op.drop_index(op.f('ix_contact_phone_number'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_api_key'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_bingwaoffer_active'), table_name='bingwaoffer')
    op.drop_table('bingwaoffer')
    # ### end Alembic commands ###
