services:
  postgres:
    image: postgres:16
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  fastapi:
    image: daviekaranja254/mazeltov:0.0.2
    container_name: backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SQLALCHEMY_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    # command: python start.py
    command: sh -c "alembic upgrade head && python start.py"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/health"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s

  frontend:
    image: daviekaranja254/mazeltov-website:0.0.3
    container_name: frontend
    restart: unless-stopped
    environment:
      - AUTH_SECRET=9/R2V8R3DlKxOXpSA9f+GVnGXt6XN5On6DeyDcDBcr4=
      - AUTH_TRUST_HOST=true
      - NEXTAUTH_URL=http://localhost:3000
      # - NEXT_PUBLIC_API_BASE_URL=
      - API_BASE_URL=http://fastapi/api/v1

    ports:
      - "3000:3000"
    depends_on:
      fastapi:
        condition: service_started

    command: sh -c "npx next start -p 3000"

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
